"""added signal lines table

Revision ID: 43580b3b983e
Revises: 53299ed9d290
Create Date: 2017-03-27 19:26:51.306893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43580b3b983e'
down_revision = '53299ed9d290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_line')
    # ### end Alembic commands ###
