"""added register table

Revision ID: 53299ed9d290
Revises: ec26e9232a6a
Create Date: 2017-03-27 19:22:49.928150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53299ed9d290'
down_revision = 'ec26e9232a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('register')
    # ### end Alembic commands ###
