"""initial version

Revision ID: a9d75d93abaf
Revises: 
Create Date: 2017-03-26 12:44:23.071041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d75d93abaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addressing_mode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instruction')
    # ### end Alembic commands ###
