"""initial version

Revision ID: ec26e9232a6a
Revises: 
Create Date: 2017-03-27 03:19:32.759748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec26e9232a6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addressing_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('op_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instruction_id', sa.Integer(), nullable=True),
    sa.Column('addressing_mode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['addressing_mode_id'], ['addressing_mode.id'], ),
    sa.ForeignKeyConstraint(['instruction_id'], ['instruction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('op_code')
    op.drop_table('instruction')
    op.drop_table('addressing_mode')
    # ### end Alembic commands ###
